
export type Document = {
  id: string;
  title: string;
  author: string;
  content: string;
  summary: string;
  category: string;
  tags: string[];
  publishDate: string;
  wikipediaUrl: string;
  views: number;
  createdAt: number;
};

// In a real application, this would be a database.
// For this prototype, we use a simple in-memory array.
export let documents: Document[] = [
  {
    id: '1',
    title: 'Arne Næss and the Deep Ecology Movement',
    author: 'Arne Næss',
    content: 'Arne Dekke Eide Næss was a Norwegian philosopher who made significant contributions to the fields of environmental philosophy and social justice. He was the founder of the deep ecology movement, which advocates for a radical shift in human consciousness and a new relationship with the natural world. This document explores his key ideas and their impact on modern environmental thought, tracing the development of deep ecology from its inception to its current state. Næss argued for an inherent value in all living beings, regardless of their utility to humans, a concept he termed "biospherical egalitarianism".',
    summary: 'An exploration of Arne Næss\'s foundational role in the deep ecology movement, detailing his philosophical contributions to environmentalism, social justice, and the concept of "biospherical egalitarianism".',
    category: 'Environmental Philosophy',
    tags: ['Arne Næss', 'Deep Ecology', '20th Century'],
    publishDate: '1973-01-15',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Arne_N%C3%A6ss',
    views: 980,
    createdAt: 1673740800000,
  },
  {
    id: '2',
    title: 'The Philosophy of Peter Wessel Zapffe',
    author: 'Peter Wessel Zapffe',
    content: 'Peter Wessel Zapffe was a Norwegian metaphysician, author, and mountaineer. He is best known for his philosophically pessimistic and antinatalist worldview. His magnum opus, "On the Tragic," posits that human beings are a biological paradox, over-equipped with a consciousness that is not fit for the world. This consciousness forces humans to seek meaning in a meaningless universe, leading to inevitable suffering. Zapffe proposed four main defense mechanisms: isolation, anchoring, distraction, and sublimation, which humans use to cope with their tragic condition.',
    summary: 'A summary of Peter Wessel Zapffe\'s pessimistic and antinatalist philosophy, focusing on his work "On the Tragic" and the concept of humanity as a biological paradox doomed to suffer.',
    category: 'Metaphysics',
    tags: ['Peter Wessel Zapffe', 'Pessimism', 'Antinatalism'],
    publishDate: '1941-05-20',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Peter_Wessel_Zapffe',
    views: 950,
    createdAt: 1673654400000,
  },
  {
    id: '3',
    title: 'Existentialism in Post-War Norway',
    author: 'Jens Bjørneboe',
    content: 'The post-World War II era in Norway saw a surge in existentialist thought, influenced heavily by figures like Jean-Paul Sartre and Albert Camus, but with a distinct Norwegian character. This paper examines the works of Norwegian existentialists such as Jens Bjørneboe and Axel Sandemose and how they grappled with questions of freedom, responsibility, and meaning in a rapidly modernizing society that was also dealing with the trauma of occupation. The concept of "Jante Law" (Janteloven) as a societal constraint on individual freedom is a recurring theme.',
    summary: 'This paper discusses the rise of existentialism in post-war Norway, analyzing its unique characteristics, the influence of major European existentialists, and the grappling with concepts like "Jante Law".',
    category: 'Existentialism',
    tags: ['Post-War Philosophy', 'Norwegian Existentialism', 'Janteloven'],
    publishDate: '1955-11-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Existentialism',
    views: 720,
    createdAt: 1673568000000,
  },
  {
    id: '4',
    title: 'The Logic of Democracy by Anathon Aall',
    author: 'Anathon Aall',
    content: 'Anathon Aall was a central figure in Norwegian philosophy, bridging the 19th and 20th centuries. His work on the history of philosophy and the philosophy of religion was extensive, but his political philosophy, particularly his analysis of democracy, is noteworthy. Aall was critical of direct democracy, arguing for a more deliberative and representative model grounded in rational discourse and the protection of individual rights against the "tyranny of the majority." He believed that a healthy democracy required an educated citizenry and strong, independent institutions.',
    summary: 'An overview of Anathon Aall\'s political philosophy, focusing on his critique of direct democracy and his arguments for a representative model based on reason and individual rights.',
    category: 'Political Philosophy',
    tags: ['Anathon Aall', 'Democracy', 'Political Theory'],
    publishDate: '1918-09-10',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Anathon_Aall',
    views: 650,
    createdAt: 1673481600000,
  },
  {
    id: '5',
    title: 'Feminist Philosophy and the work of Cathrine Holst',
    author: 'Cathrine Holst',
    content: 'Contemporary Norwegian philosophy has seen significant contributions from feminist thinkers. Cathrine Holst is a prominent political philosopher whose work intersects with feminist theory, democratic theory, and the philosophy of science. She has critically examined the role of experts in policy-making and the conditions for legitimate democratic governance, often highlighting how gender biases can be embedded within supposedly neutral expertise and public discourse. Her work calls for a more inclusive and critically reflexive public sphere.',
    summary: 'An introduction to the work of contemporary feminist philosopher Cathrine Holst, exploring her analysis of democracy, expertise, and gender bias in the public sphere.',
    category: 'Feminist Philosophy',
    tags: ['Cathrine Holst', 'Feminism', 'Contemporary'],
    publishDate: '2010-06-22',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Feminist_philosophy',
    views: 510,
    createdAt: 1673395200000,
  },
  {
    id: '6',
    title: 'Scandinavian Legal Realism',
    author: 'Torfstein Eckhoff',
    content: 'The Scandinavian Legal Realism movement was a highly influential school of thought in the 20th century, with Norwegian philosopher Torstein Eckhoff as one of its key proponents. Unlike traditional legal theories that focused on abstract moral rights, the realists argued that law should be studied as an empirical, social phenomenon. Eckhoff analyzed legal norms as behavioral patterns and social facts, focusing on how judges and officials actually behave and how legal language influences their decisions. This approach sought to demystify the law and make it more predictable and scientific.',
    summary: 'A look at Scandinavian Legal Realism through the work of Torstein Eckhoff, who treated law not as abstract morals but as observable social facts and behavioral patterns.',
    category: 'Philosophy of Law',
    tags: ['Legal Realism', 'Torstein Eckhoff', 'Jurisprudence'],
    publishDate: '1966-03-05',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Scandinavian_legal_realism',
    views: 480,
    createdAt: 1673308800000,
  },
  {
    id: '7',
    title: 'The Aesthetics of Nature in Norwegian Thought',
    author: 'Various',
    content: 'The relationship with nature has been a profound and recurring theme in Norwegian culture and philosophy. This extends into aesthetics, where the sublime beauty of the Norwegian landscape—its fjords, mountains, and forests—has been a source of philosophical reflection. Thinkers have explored how these powerful natural environments shape human perception, emotion, and our sense of place in the cosmos. This aesthetic appreciation is not merely about beauty, but about the experience of awe, terror, and the sublime, linking the natural world to deep existential questions.',
    summary: 'An exploration of how the Norwegian landscape has influenced aesthetic philosophy, focusing on concepts of the sublime, awe, and nature\'s role in shaping human perception and existential reflection.',
    category: 'Aesthetics',
    tags: ['Aesthetics', 'Nature', 'Sublime'],
    publishDate: '1995-08-19',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Aesthetics_of_nature',
    views: 320,
    createdAt: 1673222400000,
  },
  {
    id: '8',
    title: 'Harald Høffding and the Philosophy of Religion',
    author: 'Harald Høffding',
    content: 'Though Danish, Harald Høffding was a monumental figure whose influence permeated Scandinavian philosophy, including Norway. His work focused on the psychology of religious experience, where he argued that the core of religion was not dogma but a feeling of dependency and a need to conserve value in the universe. He analyzed religious faith as a practical postulate, necessary for living a meaningful life, rather than a matter of theoretical proof. His empirical and psychological approach to religion was groundbreaking for its time.',
    summary: 'A look at Harald Høffding\'s significant influence on Norwegian philosophy of religion, focusing on his psychological analysis of faith as a need to conserve value.',
    category: 'Philosophy of Religion',
    tags: ['Harald Høffding', 'Psychology of Religion', 'Value Theory'],
    publishDate: '1906-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Harald_H%C3%B8ffding',
    views: 410,
    createdAt: 1704105600000,
  },
  {
    id: '9',
    title: 'Niels Treschow and the Norwegian Enlightenment',
    author: 'Niels Treschow',
    content: 'Niels Treschow was a key figure in the Scandinavian Enlightenment and the first professor of philosophy at the University of Oslo (then Royal Frederick University). He was a rationalist who sought to reconcile Enlightenment ideals with a mild form of Christianity. His philosophy was anthropocentric, emphasizing human reason, freedom, and the potential for moral and intellectual development. He wrote extensively on psychology, pedagogy, and the philosophy of the state, advocating for education and enlightened governance as the pillars of a progressive society.',
    summary: 'An exploration of Niels Treschow, a leading Norwegian Enlightenment thinker, and his rationalist philosophy emphasizing human reason, education, and progressive governance.',
    category: 'Enlightenment Philosophy',
    tags: ['Niels Treschow', 'Enlightenment', 'Rationalism'],
    publishDate: '1812-05-12',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Niels_Treschow',
    views: 380,
    createdAt: 1704192000000,
  },
  {
    id: '10',
    title: 'The Philosophy of Science in Norway: The Oslo School',
    author: 'Ingebrigt Johansson',
    content: 'The Oslo School was a group of philosophers active in the mid-20th century who made significant contributions to the philosophy of science and logic. Figures like Ingebrigt Johansson and Albert Lange Fliflet worked on topics ranging from the foundations of mathematics to the logic of scientific discovery. They were influenced by logical positivism but maintained a critical distance, often emphasizing the role of conventionality and practical considerations in scientific theories. This school of thought helped establish a strong tradition of analytic philosophy in Norway.',
    summary: 'A review of the Oslo School in the mid-20th century, highlighting its contributions to the philosophy of science and logic, and its role in establishing analytic philosophy in Norway.',
    category: 'Philosophy of Science',
    tags: ['Oslo School', 'Analytic Philosophy', 'Logic'],
    publishDate: '1952-09-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Philosophy_of_science',
    views: 295,
    createdAt: 1704278400000,
  },
  {
    id: '11',
    title: 'Ludvig Holberg: The Father of Modern Norwegian Literature and Thought',
    author: 'Ludvig Holberg',
    content: 'Ludvig Holberg, a writer, philosopher, historian, and playwright, is considered a foundational figure in the Dano-Norwegian cultural sphere. His work is steeped in the ideas of the Enlightenment, promoting reason, moderation, and empirical observation. Through his satirical plays and essays, he critiqued religious dogmatism, social hypocrisy, and outdated traditions. Philosophically, he introduced and popularized new European ideas in Scandinavia, advocating for natural law, religious tolerance, and a rational approach to human affairs. His influence shaped the intellectual landscape of Norway for generations.',
    summary: 'An analysis of Ludvig Holberg, who brought Enlightenment ideas of reason, satire, and natural law to Scandinavia, profoundly shaping modern Norwegian literature and philosophy.',
    category: 'Enlightenment Philosophy',
    tags: ['Ludvig Holberg', 'Satire', 'Natural Law'],
    publishDate: '1741-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Ludvig_Holberg',
    views: 880,
    createdAt: 1704364800000,
  },
  {
    id: '12',
    title: 'Hans Skjervheim and the Critique of Objectivism',
    author: 'Hans Skjervheim',
    content: 'Hans Skjervheim was a prominent 20th-century Norwegian philosopher known for his critique of scientism and objectivism, particularly in the social sciences. Drawing from phenomenology and hermeneutics, he argued that human beings cannot be studied as mere objects, because they are participants in the world they inhabit. His famous essay "The Participant and the Spectator" distinguishes between the external, objective stance of a spectator and the internal, engaged perspective of a participant. For Skjervheim, true understanding of human action requires acknowledging this participatory dimension.',
    summary: 'A review of Hans Skjervheim\'s critique of objectivism in the social sciences, focusing on his distinction between the "participant" and "spectator" perspectives.',
    category: 'Phenomenology',
    tags: ['Hans Skjervheim', 'Hermeneutics', 'Critique of Scientism'],
    publishDate: '1957-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Hans_Skjervheim',
    views: 455,
    createdAt: 1704451200000,
  },
  {
    id: '13',
    title: 'Marcus Jacob Monrad: Norwegian Hegelianism',
    author: 'Marcus Jacob Monrad',
    content: 'Marcus Jacob Monrad was the leading proponent of Hegelian philosophy in Norway during the 19th century. He adapted Georg Wilhelm Friedrich Hegel\'s system to a Norwegian context, emphasizing the role of the state, Christianity, and national culture as manifestations of the Absolute Spirit. Monrad was a conservative thinker who saw the state as a moral and spiritual entity responsible for guiding the development of its people. His idealist philosophy stood in contrast to the growing empiricism and materialism of his time, sparking significant intellectual debate.',
    summary: 'An examination of Marcus Jacob Monrad and his role in introducing and adapting Hegelian idealism to 19th-century Norway, emphasizing his conservative views on the state and culture.',
    category: 'Idealism',
    tags: ['Marcus Jacob Monrad', 'Hegelianism', '19th Century'],
    publishDate: '1850-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Marcus_Jacob_Monrad',
    views: 210,
    createdAt: 1704537600000,
  },
  {
    id: '14',
    title: 'The Bioethics of Asbjørn Eide',
    author: 'Asbjørn Eide',
    content: 'Asbjørn Eide is a distinguished Norwegian jurist and scholar who has made significant contributions to the field of human rights and bioethics. His work explores the ethical dilemmas arising from advancements in medicine and biotechnology. Eide champions a human rights-based approach to bioethics, arguing that principles of dignity, equality, and non-discrimination must guide policy and practice. He has written on topics such as the right to health, the ethics of genetic engineering, and the protection of vulnerable populations in medical research, influencing international law and policy.',
    summary: 'An overview of Asbjørn Eide\'s contributions to bioethics, focusing on his human rights-based approach to issues like the right to health and genetic engineering.',
    category: 'Ethics',
    tags: ['Asbjørn Eide', 'Bioethics', 'Human Rights'],
    publishDate: '1998-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Asbj%C3%B8rn_Eide',
    views: 315,
    createdAt: 1704624000000,
  },
  {
    id: '15',
    title: 'Dagfinn Føllesdal and Quine\'s Influence in Scandinavia',
    author: 'Dagfinn Føllesdal',
    content: 'Dagfinn Føllesdal is a leading contemporary Norwegian philosopher, known for his work in phenomenology, philosophy of language, and for introducing the philosophy of W.V.O. Quine to Scandinavia. Føllesdal masterfully bridged the analytic and continental traditions. His research on Husserl\'s phenomenology, interpreted through the lens of analytic philosophy, opened up new avenues for understanding meaning, reference, and intentionality. His close association with Quine helped embed a rigorous, analytic approach within the Norwegian philosophical landscape.',
    summary: 'An exploration of Dagfinn Føllesdal\'s work, highlighting his role in bridging analytic and continental philosophy and popularizing the ideas of W.V.O. Quine in Norway.',
    category: 'Philosophy of Language',
    tags: ['Dagfinn Føllesdal', 'W.V.O. Quine', 'Phenomenology'],
    publishDate: '1982-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Dagfinn_F%C3%B8llesdal',
    views: 550,
    createdAt: 1704710400000,
  },
  {
    id: '16',
    title: 'Gunnar Skirbekk: Modernity and Rationality',
    author: 'Gunnar Skirbekk',
    content: 'Gunnar Skirbekk is a Norwegian philosopher associated with the Frankfurt School and discourse ethics. His work centers on the concepts of modernity, rationality, and transcendental pragmatics. Skirbekk argues for a form of procedural, communicative rationality as the foundation for ethical and political discourse in modern, pluralistic societies. He defends the project of modernity against postmodern critiques, suggesting that while modernity has its pathologies, its core ideals of reason and universalism are worth preserving through critical reflection and open dialogue.',
    summary: 'A look at Gunnar Skirbekk\'s defense of modernity and communicative rationality, influenced by the Frankfurt School, as a basis for discourse in pluralistic societies.',
    category: 'Critical Theory',
    tags: ['Gunnar Skirbekk', 'Modernity', 'Discourse Ethics'],
    publishDate: '1993-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Gunnar_Skirbekk',
    views: 280,
    createdAt: 1704796800000,
  },
  {
    id: '17',
    title: 'Norwegian Scholasticism in the Middle Ages',
    author: 'Unknown',
    content: 'While Norway was on the periphery of medieval Europe, scholastic philosophy still found its way into the intellectual life of the clergy and monastic orders. Thinkers at cathedral schools in Trondheim, Bergen, and Oslo would have been educated in the traditions of Aristotelian logic and theology, as interpreted by figures like Thomas Aquinas and Duns Scotus. While few original philosophical works survive from this period, records show a curriculum focused on the trivium (grammar, logic, rhetoric) and quadrivium, indicating a solid grounding in the scholastic method and its concerns with faith and reason.',
    summary: 'An overview of the presence of scholastic philosophy in medieval Norway, focusing on the education of clergy in Aristotelian logic and theology within cathedral schools.',
    category: 'Medieval Philosophy',
    tags: ['Scholasticism', 'Middle Ages', 'Theology'],
    publishDate: '1350-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Scholasticism',
    views: 150,
    createdAt: 1704883200000,
  },
  {
    id: '18',
    title: 'Herman Tønnessen: Anarchism and Radical Pessimism',
    author: 'Herman Tønnessen',
    content: 'Herman Tønnessen was a Norwegian-American philosopher and a colleague of Arne Næss. He was known for his radical and often provocative views, combining elements of anarchism, skepticism, and a Zapffe-inspired pessimism. Tønnessen was a harsh critic of established institutions, social norms, and what he saw as the irrationality of human behavior. He employed logical analysis to deconstruct common beliefs and ideologies, arguing that much of human striving is absurd. His work challenges readers to confront uncomfortable truths about society and the human condition.',
    summary: 'An introduction to the radical philosophy of Herman Tønnessen, exploring his blend of anarchism, skepticism, and pessimistic critique of social institutions and human behavior.',
    category: 'Anarchism',
    tags: ['Herman Tønnessen', 'Skepticism', 'Radical Philosophy'],
    publishDate: '1970-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Herman_T%C3%B8nnessen',
    views: 390,
    createdAt: 1704969600000,
  },
  {
    id: '19',
    title: 'The Logic of Norms by Jon Elster',
    author: 'Jon Elster',
    content: 'Jon Elster is a highly influential Norwegian social and political theorist, known for his work on rational choice theory and his critiques of it. In "The Logic of Norms," and other works, he explores why people follow social norms, even when it goes against their immediate self-interest. Elster distinguishes between rational action, driven by consequences, and action guided by social norms. He analyzes the often-contradictory nature of norms and their powerful role in sustaining social order, cooperation, and collective action. His work draws on philosophy, history, and social science.',
    summary: 'A summary of Jon Elster\'s analysis of social norms, exploring why people adhere to them and how they function as a mechanism for social order, distinct from rational self-interest.',
    category: 'Social Philosophy',
    tags: ['Jon Elster', 'Social Norms', 'Rational Choice Theory'],
    publishDate: '1989-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Jon_Elster',
    views: 610,
    createdAt: 1705056000000,
  },
  {
    id: '20',
    title: 'Knut Erik Tranøy and the Ethics of Medicine',
    author: 'Knut Erik Tranøy',
    content: 'Knut Erik Tranøy was a pioneer of medical ethics and philosophy of science in Norway. He was instrumental in establishing ethics as a formal part of medical education and research. Tranøy advocated for a humanistic and patient-centered approach to medicine, emphasizing informed consent, patient autonomy, and the social responsibilities of doctors. He argued that scientific facts alone are insufficient for making medical decisions, which always involve values and ethical judgments. His work laid the foundation for the institutionalization of bioethics in Norway.',
    summary: 'An overview of Knut Erik Tranøy\'s pioneering work in medical ethics in Norway, emphasizing his humanistic, patient-centered approach and the role of values in medicine.',
    category: 'Ethics',
    tags: ['Knut Erik Tranøy', 'Medical Ethics', 'Philosophy of Science'],
    publishDate: '1986-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Bioethics',
    views: 240,
    createdAt: 1705142400000,
  },
  {
    id: '21',
    title: 'The Reformation\'s Impact on Norwegian Philosophy',
    author: 'Various',
    content: 'The Protestant Reformation in the 16th century profoundly reshaped the intellectual and religious landscape of Norway. The shift from Catholicism to Lutheranism replaced the scholastic tradition with a new focus on individual faith, scripture, and a direct relationship with God. Humanist ideas, emphasizing classical learning and textual criticism, also gained prominence. Figures like Absalon Pederssøn Beyer represented this new learning, combining theological concerns with a burgeoning national-historical consciousness. This period moved the center of intellectual authority from the church hierarchy to the state and the university.',
    summary: 'An analysis of how the Protestant Reformation transformed Norwegian intellectual life, shifting the philosophical focus from scholasticism to individual faith and humanist learning.',
    category: 'Renaissance Philosophy',
    tags: ['Reformation', 'Humanism', 'Lutheranism'],
    publishDate: '1537-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Reformation',
    views: 180,
    createdAt: 1705228800000,
  },
  {
    id: '22',
    title: 'Jakob Sverdrup and the Philosophy of Education',
    author: 'Jakob Sverdrup',
    content: 'Jakob Sverdrup, a 19th-century educator and theologian, was a key figure in reforming the Norwegian education system. His philosophy of education was rooted in a Christian-humanist tradition, but he also stressed the importance of "dannelse" (a broad, personal formation of character and culture) for all citizens, not just the elite. He championed the establishment of folk high schools, which aimed to provide a practical and moral education for the rural population, fostering democratic values and a sense of national identity. His work reflects a belief in education as a tool for both personal and societal enlightenment.',
    summary: 'A look at Jakob Sverdrup\'s 19th-century philosophy of education, which blended Christian-humanist ideals with the promotion of "dannelse" (personal formation) through folk high schools.',
    category: 'Philosophy of Education',
    tags: ['Jakob Sverdrup', 'Pedagogy', 'Folk High School'],
    publishDate: '1864-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Folk_high_school',
    views: 265,
    createdAt: 1705315200000,
  },
  {
    id: '23',
    title: 'Stein Rokkan: A Model for Political Science',
    author: 'Stein Rokkan',
    content: 'Stein Rokkan was a pioneering Norwegian political scientist and sociologist whose work had deep philosophical underpinnings. He is famous for his macro-historical models of state formation and nation-building in Europe. Rokkan developed a set of conceptual maps to explain how political cleavages (like class, religion, and urban-rural divides) structure national party systems. His work is a monumental attempt to create a systematic, almost scientific, framework for understanding political development, blending history, sociology, and political theory.',
    summary: 'An overview of Stein Rokkan\'s influential models of state formation and political cleavages, which provided a systematic framework for understanding how party systems develop in Europe.',
    category: 'Political Philosophy',
    tags: ['Stein Rokkan', 'Political Science', 'Nation-Building'],
    publishDate: '1970-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Stein_Rokkan',
    views: 750,
    createdAt: 1705401600000,
  },
  {
    id: '24',
    title: 'The Ethics of War and Peace: Henrik Syse',
    author: 'Henrik Syse',
    content: 'Henrik Syse is a contemporary Norwegian philosopher specializing in the ethics of war, peace, and international relations. His work often engages with the Just War tradition, examining the moral criteria for engaging in and conducting warfare. Syse analyzes the challenges that modern phenomena like terrorism, humanitarian intervention, and autonomous weapons pose to traditional ethical frameworks. He argues for a robust public and philosophical debate on security and defense, grounded in both realism and a strong commitment to human rights and international law.',
    summary: 'An exploration of contemporary philosopher Henrik Syse\'s work on the ethics of war and peace, focusing on his application of Just War theory to modern challenges like terrorism and intervention.',
    category: 'Ethics',
    tags: ['Henrik Syse', 'Just War Theory', 'Peace Studies'],
    publishDate: '2005-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Just_war_theory',
    views: 340,
    createdAt: 1705488000000,
  },
  {
    id: '25',
    title: 'Axel Honneth\'s Influence on Norwegian Critical Theory',
    author: 'Various',
    content: 'While German, Axel Honneth\'s "struggle for recognition" has been highly influential in contemporary Norwegian social philosophy and critical theory. Norwegian thinkers have applied Honneth\'s framework—which posits that social struggles are driven by a desire for recognition in the spheres of love (private relations), rights (legal relations), and solidarity (community)—to analyze Norwegian society. This includes studies on welfare state policies, multiculturalism, and labor relations, examining whether these institutions foster or hinder mutual recognition among citizens.',
    summary: 'A look at how Norwegian social philosophers have applied German thinker Axel Honneth\'s theory of recognition to analyze the welfare state, multiculturalism, and social solidarity in Norway.',
    category: 'Critical Theory',
    tags: ['Axel Honneth', 'Recognition Theory', 'Social Philosophy'],
    publishDate: '2015-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Axel_Honneth',
    views: 420,
    createdAt: 1705574400000,
  },
  {
    id: '26',
    title: 'Thoralf Skolem and the Foundations of Mathematics',
    author: 'Thoralf Skolem',
    content: 'Thoralf Skolem was a Norwegian mathematician and logician who made groundbreaking contributions to the foundations of mathematics, mathematical logic, and set theory. His work, including Skolem\'s paradox and the Löwenheim–Skolem theorem, had profound philosophical implications, challenging conceptions of infinity and the nature of mathematical truth. He was a key figure in the development of first-order logic and model theory, and his constructivist leanings influenced philosophical debates about the existence of mathematical objects.',
    summary: 'An overview of Thoralf Skolem\'s pivotal work in mathematical logic and set theory, and its philosophical implications for understanding infinity and mathematical truth.',
    category: 'Logic',
    tags: ['Thoralf Skolem', 'Logic', 'Set Theory', 'Philosophy of Mathematics'],
    publishDate: '1922-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Thoralf_Skolem',
    views: 310,
    createdAt: 1705660800000,
  },
  {
    id: '27',
    title: 'The Philosophy of Global Justice: Thomas Pogge\'s Norwegian Connection',
    author: 'Thomas Pogge',
    content: 'Though German-American, Thomas Pogge has held professorships in Norway and his work on global justice and poverty is widely discussed in Norwegian philosophical circles. He is a prominent critic of the current global institutional order, arguing that it systematically disadvantages the poor. Pogge posits that citizens of wealthy nations have a negative duty not to impose an unjust global structure on others. His work challenges traditional notions of charity and advocates for structural reforms to address global inequality.',
    summary: 'An exploration of Thomas Pogge\'s theory of global justice, influential in Norway, which argues for a duty to reform unjust global institutions that perpetuate poverty.',
    category: 'Political Philosophy',
    tags: ['Thomas Pogge', 'Global Justice', 'Poverty', 'Cosmopolitanism'],
    publishDate: '2002-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Thomas_Pogge',
    views: 450,
    createdAt: 1705747200000,
  },
  {
    id: '28',
    title: 'Camilla Collett and the Dawn of Norwegian Feminism',
    author: 'Camilla Collett',
    content: 'Camilla Collett is considered one of the first and most influential feminists in Norwegian history. Her most famous novel, "The District Governor\'s Daughters" (Amtmandens Døtre), is a powerful critique of the institution of marriage and the lack of educational and emotional freedom for women in 19th-century society. Through her essays and literary work, Collett championed women\'s right to an emotional and intellectual life of their own, laying the groundwork for the later women\'s rights movement. Her philosophy was one of personal emancipation and social critique.',
    summary: 'An introduction to Camilla Collett, Norway\'s pioneering feminist thinker, whose novel "The District Governor\'s Daughters" critiqued patriarchal society and advocated for women\'s emancipation.',
    category: 'Feminist Philosophy',
    tags: ['Camilla Collett', 'Feminism', '19th Century', 'Social Critique'],
    publishDate: '1854-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Camilla_Collett',
    views: 680,
    createdAt: 1705833600000,
  },
  {
    id: '29',
    title: 'The Philosophy of Work and Leisure',
    author: 'Lars Fredrik Svendsen',
    content: 'Contemporary Norwegian philosopher Lars Fredrik Svendsen has written extensively on topics that intersect with everyday life, including the philosophy of work and leisure. He analyzes the modern concept of work, its relation to identity, and the "workaholic" culture. Svendsen contrasts this with the idea of leisure, not as mere idleness, but as a space for freedom, play, and meaningful activity that is valuable in itself. His work draws on a wide range of philosophers to explore how we can live more balanced and fulfilling lives in the modern world.',
    summary: 'A look at Lars Fredrik Svendsen\'s philosophical analysis of modern work culture, identity, and the importance of meaningful leisure for a balanced life.',
    category: 'Social Philosophy',
    tags: ['Lars Fredrik Svendsen', 'Work', 'Leisure', 'Contemporary'],
    publishDate: '2008-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Lars_Fr._H._Svendsen',
    views: 490,
    createdAt: 1705920000000,
  },
  {
    id: '30',
    title: 'Norse Mythology and its Philosophical Themes',
    author: 'Unknown',
    content: 'Norse mythology, preserved in texts like the Poetic Edda, contains rich philosophical themes that shaped the worldview of pre-Christian Scandinavia. Concepts of fate (wyrd), the cyclical nature of creation and destruction (Ragnarök), the tension between order (cosmos) and chaos (giants), and the ethical code of honor and courage in the face of a harsh world, all offer deep material for philosophical reflection. This article explores the underlying metaphysics, ethics, and cosmology of the Norse belief system.',
    summary: 'An exploration of the philosophical themes within Norse mythology, including concepts of fate, honor, and the cyclical nature of existence as seen in texts like the Poetic Edda.',
    category: 'Mythology & Folklore',
    tags: ['Norse Mythology', 'Edda', 'Cosmology', 'Ethics'],
    publishDate: '1200-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Norse_mythology',
    views: 890,
    createdAt: 1706006400000,
  },
  {
    id: '31',
    title: 'Jonas Gahr Støre and the Politics of Dialogue',
    author: 'Jonas Gahr Støre',
    content: 'Before becoming Prime Minister, Jonas Gahr Støre was a political scientist and diplomat whose thinking was shaped by a philosophical commitment to dialogue. Drawing from his experience in peace processes, Støre has emphasized the importance of engagement, even with adversaries, as a core principle of foreign policy and social cohesion. This philosophy argues against isolation and for the power of communication to resolve conflicts and build trust, reflecting a pragmatic and deeply humanistic approach to politics.',
    summary: 'An analysis of the political philosophy of Jonas Gahr Støre, focusing on his emphasis on dialogue, engagement, and communication as key tools for conflict resolution and foreign policy.',
    category: 'Political Philosophy',
    tags: ['Jonas Gahr Støre', 'Diplomacy', 'Dialogue', 'International Relations'],
    publishDate: '2008-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Jonas_Gahr_St%C3%B8re',
    views: 330,
    createdAt: 1706092800000,
  },
  {
    id: '32',
    title: 'The Philosophical Underpinnings of the Norwegian Constitution',
    author: 'Various',
    content: 'The Norwegian Constitution of 1814 is a product of Enlightenment ideals, heavily influenced by the separation of powers doctrine of Montesquieu and the concept of popular sovereignty from Rousseau. It represents a philosophical commitment to individual liberty, the rule of law, and representative government. This article examines the key philosophical principles that informed the writers at Eidsvoll, and how these principles have been interpreted and adapted throughout Norway\'s history, balancing individual rights with the power of the state.',
    summary: 'An examination of the Enlightenment philosophy, from thinkers like Montesquieu and Rousseau, that shaped the Norwegian Constitution of 1814 and its principles of liberty and governance.',
    category: 'Philosophy of Law',
    tags: ['Constitution', 'Enlightenment', 'Separation of Powers', 'Sovereignty'],
    publishDate: '1814-05-17',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Constitution_of_Norway',
    views: 520,
    createdAt: 1706179200000,
  },
  {
    id: '33',
    title: 'The Ethics of Artificial Intelligence in a Nordic Context',
    author: 'Trygve Lavik',
    content: 'The rapid development of Artificial Intelligence (AI) raises profound ethical questions. Norwegian philosophers are actively engaged in this debate, focusing on issues of fairness, transparency, and accountability in algorithmic systems. A key concern is how to align AI development with the Nordic model\'s values of social trust, equality, and a strong public sector. This involves scrutinizing AI for biases, ensuring democratic oversight, and debating the future of work in an automated age.',
    summary: 'An overview of the ethical debate around AI in Norway, focusing on aligning algorithms with Nordic values like trust and equality, and ensuring fairness and accountability.',
    category: 'Technoethics',
    tags: ['AI Ethics', 'Algorithms', 'Nordic Model', 'Trygve Lavik'],
    publishDate: '2021-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Ethics_of_artificial_intelligence',
    views: 390,
    createdAt: 1706265600000,
  },
  {
    id: '34',
    title: 'Animal Rights and the Norwegian Legal System',
    author: 'Siri Martinsen',
    content: 'The philosophical debate on animal rights has had a tangible impact in Norway, led by figures like Siri Martinsen and the organization NOAH. This movement challenges the traditional view of animals as mere property, arguing for their status as sentient beings with interests that deserve legal protection. The philosophical arguments draw from utilitarianism (minimizing suffering) and rights-based theories, leading to reforms in animal welfare law and public consciousness about animal exploitation in industry and research.',
    summary: 'An analysis of the animal rights movement in Norway, its philosophical foundations in utilitarian and rights-based ethics, and its influence on changing legal and social attitudes towards animals.',
    category: 'Animal Ethics',
    tags: ['Animal Rights', 'Siri Martinsen', 'NOAH', 'Animal Welfare'],
    publishDate: '2010-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Animal_rights',
    views: 350,
    createdAt: 1706352000000,
  },
  {
    id: '35',
    title: 'Cosmopolitanism in Norwegian Philosophy',
    author: 'Pauline Kleingeld',
    content: 'While national identity is a strong theme, many Norwegian thinkers have also engaged with cosmopolitanism—the idea that all human beings belong to a single community. This philosophy explores the moral obligations we have to people beyond our borders, questioning the primacy of national allegiance. Contemporary discussions in Norway touch on issues like immigration, climate change, and global economic justice, debating the tension between national duties and our duties to humanity as a whole. This reflects the Kantian tradition of perpetual peace and universal hospitality.',
    summary: 'An examination of cosmopolitan thought in Norwegian philosophy, exploring the moral obligations to global humanity and the tension between national and universal duties.',
    category: 'Political Philosophy',
    tags: ['Cosmopolitanism', 'Global Ethics', 'Kant', 'Immigration'],
    publishDate: '2012-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cosmopolitanism',
    views: 290,
    createdAt: 1706438400000,
  },
  {
    id: '36',
    title: 'The Philosophy of Landscape and Place (Sted)',
    author: 'Egil Grip',
    content: 'Beyond general aesthetics of nature, some Norwegian thinkers have focused on the specific philosophy of "sted" (place). This goes beyond seeing a landscape as a beautiful object and instead investigates the deep, existential connection between people and their specific environments. It explores how a place—a farm, a valley, a coastline—shapes identity, memory, and a sense of belonging. This phenomenological approach emphasizes lived experience and the intricate web of culture, history, and nature that constitutes a "place".',
    summary: 'An exploration of the Norwegian philosophical concept of "sted" (place), examining the existential connection between people, identity, memory, and their lived environment.',
    category: 'Phenomenology',
    tags: ['Place', 'Landscape', 'Identity', 'Existentialism'],
    publishDate: '2009-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Place_identity',
    views: 260,
    createdAt: 1706524800000,
  },
  {
    id: '37',
    title: 'Rationality and Irrationality in Human Action',
    author: 'Jon Elster',
    content: 'Jon Elster\'s work frequently returns to the theme of human irrationality. In books like "Ulysses and the Sirens" and "Sour Grapes," he uses insights from philosophy and social science to explore the many ways humans fail to act rationally. He analyzes phenomena like weakness of will (akrasia), adaptive preference formation (sour grapes), and our tendency to use pre-commitment strategies to bind our future selves. Elster\'s analysis is a philosophical deep-dive into the quirks and contradictions of the human mind.',
    summary: 'A summary of Jon Elster\'s exploration of human irrationality, including concepts like weakness of will, adaptive preferences, and pre-commitment strategies.',
    category: 'Philosophy of Mind',
    tags: ['Jon Elster', 'Irrationality', 'Rational Choice', 'Akrasia'],
    publishDate: '1979-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Irrationality',
    views: 580,
    createdAt: 1706611200000,
  },
  {
    id: '38',
    title: 'The Sami Understanding of Nature and Reality',
    author: 'Various',
    content: 'The indigenous Sami people of Norway possess a rich worldview with deep philosophical dimensions. Traditional Sami cosmology does not draw a sharp line between humans and nature; instead, it sees the world as a web of interconnected beings and forces. Animals, stones, and landscapes can have spirit and agency. This animistic and shamanistic understanding of reality, where the spiritual and material worlds are intertwined, offers a profound alternative to Western dualism and has influenced contemporary environmental philosophy.',
    summary: 'An exploration of the indigenous Sami worldview, highlighting its non-dualistic and animistic understanding of nature, where all elements are seen as interconnected spiritual beings.',
    category: 'Indigenous Philosophy',
    tags: ['Sami', 'Animism', 'Cosmology', 'Indigenous Knowledge'],
    publishDate: '1900-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Sami_shamanism',
    views: 510,
    createdAt: 1706697600000,
  },
  {
    id: '39',
    title: 'The Philosophy of Ibsen\'s plays',
    author: 'Henrik Ibsen',
    content: 'While primarily a playwright, Henrik Ibsen\'s works are saturated with philosophical questions that had a massive impact on European thought. Plays like "A Doll\'s House," "Ghosts," and "An Enemy of the People" are powerful explorations of individualism, social hypocrisy, female emancipation, and the struggle for truth against societal convention. Ibsen put complex ethical dilemmas on stage, forcing his audience to confront the moral compromises of modern life. He is often seen as a key figure in the development of theatrical modernism and a dramatist of ideas.',
    summary: 'An analysis of the profound philosophical themes in Henrik Ibsen\'s plays, including individualism, social critique, and the struggle for truth, which made him a "dramatist of ideas."',
    category: 'Literature & Philosophy',
    tags: ['Henrik Ibsen', 'Individualism', 'Modernism', 'Theatre'],
    publishDate: '1879-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Henrik_Ibsen',
    views: 920,
    createdAt: 1706784000000,
  },
  {
    id: '40',
    title: 'The Problem of Evil: A Norwegian Perspective',
    author: 'Lars Fr. H. Svendsen',
    content: 'In his "A Philosophy of Evil," Lars Fredrik Svendsen tackles one of philosophy\'s oldest problems. He examines different conceptions of evil—demonic, instrumental, idealistic, and stupid—drawing on historical events and philosophical theories from Kant to Arendt. Svendsen argues against seeing evil as a mysterious, radical force. Instead, he often frames it as a banal, human phenomenon born from a lack of empathy and a failure of moral imagination. His work seeks to understand evil in order to better resist it.',
    summary: 'A review of Lars Fredrik Svendsen\'s "A Philosophy of Evil," which analyzes different conceptions of evil and frames it not as a mystical force but as a banal human phenomenon.',
    category: 'Ethics',
    tags: ['Lars Fredrik Svendsen', 'Problem of Evil', 'Arendt', 'Ethics'],
    publishDate: '2001-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Problem_of_evil',
    views: 650,
    createdAt: 1706870400000,
  },
  {
    id: '41',
    title: 'The Philosophy of Loneliness',
    author: 'Lars Fr. H. Svendsen',
    content: 'Lars Fredrik Svendsen also explores the modern experience of loneliness, distinguishing it from chosen solitude. He investigates loneliness as a social pathology, an emotional response to a lack of meaningful connection. The book traces the cultural and philosophical history of loneliness, questioning why it has become so prevalent in societies that are more connected than ever. Svendsen examines loneliness not just as a personal feeling, but as a significant social and political problem.',
    summary: 'A summary of Lars Fredrik Svendsen\'s philosophical investigation into loneliness, analyzing it as a modern social pathology distinct from solitude and a major political problem.',
    category: 'Social Philosophy',
    tags: ['Lars Fredrik Svendsen', 'Loneliness', 'Community', 'Modernity'],
    publishDate: '2015-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Loneliness',
    views: 530,
    createdAt: 1706956800000,
  },
  {
    id: '42',
    title: 'The History of Skepticism in Norway',
    author: 'Various',
    content: 'Beyond the radicalism of Herman Tønnessen, Norway has a broader tradition of philosophical and scientific skepticism. This includes the popularization of critical thinking and the scientific method as a defense against pseudoscience and dogma. Organizations and public intellectuals have played a key role in promoting skepticism as a public good, encouraging evidence-based reasoning in public discourse, from medicine to politics. This reflects a deep-seated Enlightenment value of questioning authority and demanding evidence.',
    summary: 'An overview of the tradition of scientific and philosophical skepticism in Norway, focusing on the promotion of critical thinking and evidence-based reasoning in public life.',
    category: 'Epistemology',
    tags: ['Skepticism', 'Critical Thinking', 'Pseudoscience', 'Enlightenment'],
    publishDate: '2000-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Scientific_skepticism',
    views: 310,
    createdAt: 1707043200000,
  },
  {
    id: '43',
    title: 'The Bergen School of Meteorology and its Philosophical Impact',
    author: 'Vilhelm Bjerknes',
    content: 'The Bergen School of Meteorology, founded by Vilhelm Bjerknes in the 1920s, revolutionized weather forecasting by treating it as a problem of physics. While a scientific achievement, its philosophical impact was profound. It represented a victory for a mechanistic and predictive model of nature, demonstrating that complex, seemingly chaotic systems could be understood and predicted through mathematical laws. This bolstered a positivistic and scientific worldview and had implications for the debate between determinism and free will.',
    summary: 'An analysis of the philosophical impact of the Bergen School of Meteorology, which promoted a deterministic and mathematical model of nature, influencing debates on scientific prediction.',
    category: 'Philosophy of Science',
    tags: ['Vilhelm Bjerknes', 'Determinism', 'Prediction', 'Positivism'],
    publishDate: '1920-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Bergen_School_of_Meteorology',
    views: 290,
    createdAt: 1707129600000,
  },
  {
    id: '44',
    title: 'The Concept of "Friluftsliv" (Open-Air Life)',
    author: 'Henrik Ibsen',
    content: '"Friluftsliv," a term popularized by Henrik Ibsen, describes a specifically Nordic passion for being outdoors and connecting with nature. It is more than just a hobby; it is a philosophy of well-being. It posits that spending time in the open air is essential for physical and mental health, a way to escape the pressures of modern life and find a sense of freedom and simplicity. This concept is deeply embedded in Norwegian culture and links to philosophical ideas about the good life, authenticity, and humanity\'s place in the natural world.',
    summary: 'An exploration of the Norwegian philosophy of "friluftsliv" (open-air life), its origins with Ibsen, and its connection to well-being, freedom, and a simpler, more authentic existence.',
    category: 'Lifestyle Philosophy',
    tags: ['Friluftsliv', 'Nature', 'Well-being', 'Henrik Ibsen'],
    publishDate: '1859-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Friluftsliv',
    views: 990,
    createdAt: 1707216000000,
  },
  {
    id: '45',
    title: 'The Philosophy of Social Democracy',
    author: 'Einar Gerhardsen',
    content: 'The development of the Norwegian welfare state after WWII was guided by the philosophy of Social Democracy. Thinkers and politicians like Einar Gerhardsen articulated a vision of society based on the values of equality, solidarity, and community. This philosophy is not just an economic model; it is an ethical project aiming to provide security and opportunity for all citizens, balancing the freedom of the individual with the collective responsibility of the community. It represents a "third way" between unregulated capitalism and authoritarian socialism.',
    summary: 'An analysis of the philosophy of Norwegian Social Democracy, focusing on its core values of equality and solidarity and its ethical project of building a universal welfare state.',
    category: 'Political Philosophy',
    tags: ['Social Democracy', 'Welfare State', 'Equality', 'Solidarity'],
    publishDate: '1949-01-01',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Social_democracy',
    views: 710,
    createdAt: 1707302400000,
  }
];

// Function to add a new document
export const addDocument = (doc: Omit<Document, 'id' | 'createdAt' | 'author' | 'views' | 'wikipediaUrl'> & Partial<Pick<Document, 'author' | 'views' | 'wikipediaUrl'>>) => {
  const newDoc: Document = {
    author: 'Unknown',
    views: 0,
    wikipediaUrl: '',
    ...doc,
    id: (Date.now() + Math.random()).toString(),
    createdAt: Date.now(),
  };
  documents.unshift(newDoc);
  return newDoc;
};

    